### ISSUE TITLE
Podpora alza.sk

### ISSUE THREAD

**Issue by tiborepcek** [topmonks/heureka-extension#5]
Zdravím.

Uvítal by som podporu aj pre alza.sk. Ak bude treba preklad do slovenčiny, rád pomôžem.

**Comment by junkycoder** [comment]
Díky za podnět @tiborepcek, ukázalo se, že přidat podporu pro naše slovesnké bratry bylo easy.
Rozšíření by se ti mělo samo aktualizovat na verzi 1.1.0 a požádat tě o dodatečná práva na .sk Alzu a Heureku.

Na překlad ti prdim, myslim že si rozumíme :)

**Comment by tiborepcek** [comment]
Funguje, ďakujem.

Rozumiem ti, @junkycoder, ale ak by náhodou niekto nerozumel, vieš na koho sa môžeš obrátiť... ;)
