### ISSUE TITLE
"Neviditelná ikonka" v seznamu rozšíření

### ISSUE THREAD

**Issue by michalpaukert** [topmonks/heureka-extension#7]
Momentálně je v seznamu rozšíření ikonka vidět jen pokud najedete myší na zmíněnou ikonu.
Jinak v není vidět na světlém pozadí.
![image](https://user-images.githubusercontent.com/36043389/71073856-74a9bc00-2181-11ea-92d2-ca01f4516a11.png)

**Comment by paulus-tom** [comment]
Fixed.

**Comment by junkycoder** [comment]
Jeste oteviram, poslem to ven s dalsima opravama..
